### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by KanarekLife** [Emil8250/SuperGamblino#13]
I would want to add better exception handling (to prevent just dropping full c# exception on console). Especially I would fix it when DB is not working or token is wrong.

**Comment by Emil8250** [comment]
This would be great - been meaning to do it aswell 👍

**Comment by KanarekLife** [comment]
https://github.com/Emil8250/SuperGamblino/pull/17

Well...
It started with hope to handle exceptions and I ended up integration Microsoft.Extensions.Logging and Microsoft.Extensions.Configuration into this project. We need to specify what should be logged though...
