### ISSUE TITLE
Handle aliases for bet sizes

### ISSUE THREAD

**Issue by Emil8250** [Emil8250/SuperGamblino#24]
this could include k, m, all and so on.

Fx !roulette red 1k

**Comment by KanarekLife** [comment]
I can take care of that. Assign me pls.

**Comment by KanarekLife** [comment]
Is there any list of this aliases or source that I may find them? Cause I have no idea of other aliases...

**Comment by Emil8250** [comment]
I found this list: https://officespace.zendesk.com/hc/en-us/articles/115000593531-Scientific-Notation-Large-Numbers-Guide 

I would assume that the first 4 would be enough :) 

And then maybe add all and half

**Comment by KanarekLife** [comment]
Ok, then. Thx for the info 😄
