### ISSUE TITLE
Create XP and level system

### ISSUE THREAD

**Issue by Emil8250** [Emil8250/SuperGamblino#8]
To gain xp a minimum bet size is required. This should be related to either level or current credits.

**Comment by KanarekLife** [comment]
I might implement this but someone has to describe me how should it look like (algorithm for exp needed for every level or something).

**Comment by Emil8250** [comment]
In commit https://github.com/Emil8250/SuperGamblino/commit/5f0b60ccfbd81ecbc7d9f58e5ef3f2164f4881bb I added a rough exp and level system, It still needs a way to scale exp, atm. I just give a static (almost) exp in roulette and coinflip.

**Comment by Emil8250** [comment]
Added.
